### ISSUE TITLE
[SofaPython3::SceneLoader] Missing createScene function

### ISSUE THREAD

**Issue by 123jjx321** [mimesis-inria/DeepPhysX.Sofa#1]

**Comment by RobinEnjalbert** [comment]
Hi @123jjx321 ,

I guess you tried to launch a script with the SOFA ``runSofa`` launcher.
The scripts shared in the examples cannot be run with ``runSofa`` since I did not implement a *createScene* function. You can only run them with your ``python`` interpreter (even if some scripts are launching the SOFA GUI anyway).

**Comment by 123jjx321** [comment]
Hi,
yes, that's my mistake.  However, I can not run the python script directly. it just shows: No module named " Sofa.Gui" or "module 'Sofa' has no attribute 'Core' ".  Is it because the sofa building in my computer don't contain "caribou plugin"?

**Comment by 123jjx321** [comment]
buy the way, i build the sofapython3 with "in-tree build" method

**Comment by RobinEnjalbert** [comment]
Hi, your errors may be related to your SofaPython3 environment. 
To use the SOFA bindings within a ```python``` interpreter, please make sure that you followed these steps in the [SP3 documentation](https://sofapython3.readthedocs.io/en/latest/menu/SofaPlugin.html#within-a-python3-interpreter).
Hope it will solve your problem.

**Comment by 123jjx321** [comment]
Hi, thank you for your suggestion. I solved the SofaPython3 problem. Now, I can use sofa in a python interpreter(pycharm), the terminal results shows below,(However, the SofaCaribou seems not woking)

```
j@j:~/Desktop$ python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Sofa
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/j/SOFA/v22.12.00
---------------------------------------
>>> import Sofa.Gui
[INFO]    [Sofa.Gui] Loaded qt.conf from /home/j/SOFA/v22.12.00/bin/qt.conf customized with Prefix = /home/j/SOFA/v22.12.00
>>> import SofaRuntime
>>> import Sofa.Core
>>> import Caribou
>>> import SofaCaribou
[ERROR]   [SofaRuntime] ImportError: libSofa.Core.so.23.06.99: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/j/SOFA/v22.12.00/plugins/SofaCaribou/lib/python3/site-packages/SofaCaribou/__init__.py", line 6, in <module>
    from .SofaCaribou import *
>>> 
```


Then, I tryed to use the DeepPhyX.Sofa to generate trarining data.
First, i tryed to run code in tutorial, T1~T8 seems have no big problems. 
And, I tryed to run features, the "dataGeneration" shows the following error, the offlineTraining.py, onlineTraining.py, prediction.py also showed some errors.


```
[ERROR]   [SofaRuntime] TypeError: add_points() got an unexpected keyword argument 'positions'
Traceback (most recent call last):
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Sofa/Environment/launcherSofaEnvironment.py", line 27, in <module>
    client.initialize()
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpClient.py", line 58, in initialize
    async_run(self.__initialize())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpClient.py", line 104, in __initialize
    self.environment._create_visualization(visualization_db=db)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Sofa/Environment/SofaEnvironment.py", line 189, in _create_visualization
    self.init_visualization()
  File "/home/j/DeepPhysX/Sofa/examples/features/Environment/EnvironmentDataset.py", line 54, in init_visualization
    self.factory.add_points(positions=self.MO['input'].position.value,

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/Environment/BaseEnvironmentConfig.py", line 142, in start_server
    server.initialize(visualization_db=visualization_db,
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpServer.py", line 134, in initialize
    async_run(self.__initialize(env_kwargs, visualization_db))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpServer.py", line 183, in __initialize
    await self.receive_data(loop=loop, sender=client)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpObject.py", line 111, in receive_data
    nb_bytes_fields = self.data_converter.size_from_bytes(nb_bytes_fields_b)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/BytesConverter.py", line 42, in <lambda>
    self.size_from_bytes: Callable[[bytes], int] = lambda b: self.__bytes_to_data_conversion[int.__name__](b)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/BytesConverter.py", line 34, in <lambda>
    int.__name__: lambda b: unpack('i', b)[0],
struct.error: unpack requires a buffer of 4 bytes
```


Then, i tryed the Sofa/demos/Liver/FC/dataset.py the error shows



```
/usr/bin/python3.8 /home/j/DeepPhysX/Sofa/examples/demos/Liver/FC/dataset.py 
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Warning: environment variable SOFA_ROOT is empty. Trying to guess it.
Guessed SOFA_ROOT: /home/j/SOFA/v22.12.00
---------------------------------------
Create a new directory /home/j/DeepPhysX/Sofa/examples/demos/Liver/FC/sessions/liver_data_user for this session.
Create a new directory /home/j/DeepPhysX/Sofa/examples/demos/Liver/FC/sessions/liver_data_user/dataset for this session.
[TcpIpServer] Binding to IP Address: localhost on PORT: 10000 with maximum client count: 100
[TcpIpServer] Waiting for clients...
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/j/SOFA/v22.12.00
---------------------------------------
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/j/SOFA/v22.12.00
---------------------------------------
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/j/SOFA/v22.12.00
---------------------------------------
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: /home/j/SOFA/v22.12.00
---------------------------------------
[TcpIpServer] Client n°1 connected: <socket.socket fd=10, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 10000), raddr=('127.0.0.1', 57372)>
[TcpIpServer] Client n°3 connected: <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 10000), raddr=('127.0.0.1', 57384)>
[TcpIpServer] Client n°4 connected: <socket.socket fd=12, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 10000), raddr=('127.0.0.1', 57390)>
[TcpIpServer] Client n°2 connected: <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 10000), raddr=('127.0.0.1', 57402)>
[TcpIpServer] Initializing clients...
[ERROR]   [SofaRuntime] KeyError: 'CARIBOU_INSTALL'
Traceback (most recent call last):
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Sofa/Environment/launcherSofaEnvironment.py", line 27, in <module>
    client.initialize()
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpClient.py", line 58, in initialize
    async_run(self.__initialize())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpClient.py", line 98, in __initialize
    self.environment.create()
  File "/home/j/DeepPhysX/Sofa/examples/demos/Liver/FC/Environment/LiverSofa.py", line 61, in create
    SofaRuntime.PluginRepository.addFirstPath(os.environ['CARIBOU_INSTALL'])
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/Environment/BaseEnvironmentConfig.py", line 142, in start_server
    server.initialize(visualization_db=visualization_db,
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpServer.py", line 134, in initialize
    async_run(self.__initialize(env_kwargs, visualization_db))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpServer.py", line 183, in __initialize
    await self.receive_data(loop=loop, sender=client)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/TcpIpObject.py", line 111, in receive_data
    nb_bytes_fields = self.data_converter.size_from_bytes(nb_bytes_fields_b)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/BytesConverter.py", line 42, in <lambda>
    self.size_from_bytes: Callable[[bytes], int] = lambda b: self.__bytes_to_data_conversion[int.__name__](b)
  File "/home/j/.local/lib/python3.8/site-packages/DeepPhysX/Core/AsyncSocket/BytesConverter.py", line 34, in <lambda>
    int.__name__: lambda b: unpack('i', b)[0],
struct.error: unpack requires a buffer of 4 bytes
```

i am wondering maybe it is the problem with  plugin" caribou", however, i followed the instruction of caribou, and "import Caribou" is working(maybe something wrong with import SofaCaribou)

```
>>> import Caribou
>>> import SofaCaribou
[ERROR]   [SofaRuntime] ImportError: libSofa.Core.so.23.06.99: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/j/SOFA/v22.12.00/plugins/SofaCaribou/lib/python3/site-packages/SofaCaribou/__init__.py", line 6, in <module>
    from .SofaCaribou import *
```

would you please tell me where the problems is? is it due to the wrong version? environment error?or some other things?

**Comment by RobinEnjalbert** [comment]
The errors that you have with the demos are related to you Caribou installation (it is the same issue that you have reported on the DeepPhysX Git repository, it should be solved as well).

The errors that you have with the features are a mistake that I made when I updated the [SSD](https://github.com/RobinEnjalbert/SimulationSimpleDatabase) version, thank you for reporting this. I will push a correction very soon.

**Comment by 123jjx321** [comment]
Dear RobinRnjalbert
I am a user of your DeepPhysX, thank you a lot about your kindness and patience, I can run the DeepPhysX.Sofa/Core after listen to your advice. And now, I am tring to use your framework to connect Unity3D with DeepPhysX. Simple by using collision detection in unity to get the collision point on mesh; then use socket to make communication between unity and python to send the vecotor posion of the collision point.
However, when i tryed to change the force in the Liver.py (you generate a random force, but i want to use the force that has been sent to python from unity by socket in real-time), the sokect works well, but the data seems can not went into the "async def step" to change the f I guess it may because of the "async def".
My question is do you know how to change the input force of your demos\Liver\FC\Environment\Liver.py , I mean, for example using socket or tcp to get force data in real time and send it to f? you made the liverinteratice in vedo, I want to make the exactly same thing in Unity3d

```
sock = U.UdpComms(udpIP="127.0.0.1", portTX=8000, portRX=8001, enableRX=True, suppressWarnings=True)
data = sock.ReadReceivedData()
if data!=None:
    #F_unity = np.fromstring(data)
    arr = data.strip("(")
    arr = arr.strip(")")
    arr_ = arr.split(",")
    arr_ = np.array(arr_)
    print(arr_)

    f = uniform(low=-1, high=1, size=(3,))
```

To be honestly, I am fresh student who are doing some reserach on the deep learning in soft tissue. And I will cite your work if
I got lucky enough to publish a paper.
Thanks so much for your sharing project, cause there are too few open source in "deep-learning-soft-tissue"(cutting/deformation...), which made people with little experiment like me can hardly jump into this area
